### ISSUE TITLE
Mob Drops are Very Unbalanced

### ISSUE THREAD

**Issue by Boundarybreaker** [Kolatra/Mod-Issues#1]
Divination breaks a **lot** of mob drops. All animal meets, string, zombie flesh, ender pearls, and possibly more are dropped to a 3.2% chance of dropping, when things like string and ender pearls are incredibly necessary for other mods, and the lexicon has an almost 50% drop rate from every creature, causing you to be absolutely flooded with non-stacking duplicate lexicons when you only need one. Can that be rebalanced? A better idea would be to make the lexicon craftable, and returning mob drops to their normal rates (at least for most things) is really important for other mods. Thank you.

**Comment by Kolatra** [comment]
The Lexicon is craftable... The loot table changes in 1.9 may have affected more than I thought. I'll take a look later.

**Comment by Boundarybreaker** [comment]
I think the mob table auto-balances. I removed Divination and mob drops went back to their normal rates.

**Comment by Kolatra** [comment]
Okay, I'll look at it when I get a chance. Thank you! :)

**Comment by Kolatra** [comment]
Yes, it looks like I was adding to the entire Loot Table, and not just the world bonus chest like I had intended. Fixed for next release.
